trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '{{ azureRmConnection.Id }}'

  # Web app name
  webAppName: '{{ webAppName }}'
  
  # Environment name
  environmentName: '{{ webAppName }}'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  


stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    - task: gulp@1
      inputs:
        targets: 
        arguments: 'boo'
        workingDirectory: '/'
        enableCodeCoverage: false
    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

