trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '{{ azureRmConnection.Id }}'

  # Web app name
  webAppName: '{{ webAppName }}'
  
  # Environment name
  environmentName: '{{ webAppName }}'

  # Agent VM image name
  vmImageName: 'vs2017-win2016'
  


stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - task: gulp@1
      inputs:
        gulpFile: 'gulpfile.js' 
        targets: # Optional
        arguments: # Optional
        workingDirectory: # Optional
        gulpjs: # Optional
        testResultsFiles: '/' # Required when publishJUnitResults == True
        testRunTitle: # Optional
        enableCodeCoverage: false 
        testFramework: 'Mocha' # Optional. Options: mocha, jasmine
        srcFiles: # Optional
        testFiles: 'test/*.js' # Required when enableCodeCoverage == True
